name: MyfirstWorkflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print hello world
        run: echo "hello world by first job"
      - name: another world print
        run: echo "another world print by me"
      - name: apache script
        run: |
          sudo apt-get update -y
          sudo apt-get install httpd -y
          sudo systemctl start httpd
          sudo systemctl status httpd
          sudo systemctl restart httpd
